export const SET_FILTER = "SET_FILTER"
export const CLEAR_FILTER = "CLEAR_FILTER"
export const SET_PAGINATION = "SET_PAGINATION"
export const SELECT_MOVIE = "SELECT_MOVIE"

export const SEARCH_SUGGESTION_ACTIVATED = "SEARCH_SUGGESTION_ACTIVATED"
export const SEARCH_SUGGESTION_DISABLED = "SEARCH_SUGGESTION_DISABLED"

export const SEARCH_ITEM_BY_NAME = "SEARCH_ITEM_BY_NAME"
export const SEARCH_ITEM_BY_STAR = "SEARCH_ITEM_BY_STAR"
